name: Ubuntu RDP via Tailscale (A)

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Run 5-minute test loop"
        type: boolean
        default: false
      runtime_minutes:
        description: "Runtime in minutes (max 360; capped to 355)"
        required: false
        default: "355"
      loops:
        description: "How many handoffs (0 = infinite)"
        required: false
        default: "0"

concurrency:
  group: tailscale-rdp-singleton
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

env:
  # --- Fixed credentials/identifiers (EDIT THESE) ---
  TS_TAILNET: "wadide55@gmail.com"
  TS_APIKEY: "tskey-auth-kg1JajUh5H11CNTRL-i9kZ8H35AdeWUTScYtKhdeq3vpwPrgfsb"

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Update system
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${TS_APIKEY} --hostname=ubuntu-rdp --accept-routes --accept-dns

      - name: Install RDP (xrdp + XFCE4)
        run: |
          sudo apt-get install -y xrdp xfce4 xfce4-goodies dbus-x11 x11-xserver-utils
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Create RDP user
        run: |
          sudo useradd -m -s /bin/bash rdpuser || true
          echo "rdpuser:password123" | sudo chpasswd
          sudo usermod -aG sudo rdpuser

      - name: Run session
        run: |
          echo "RDP session is live. Use your Tailscale IP with RDP client."
          echo "Username: rdpuser | Password: password123"
          sleep $(( ${{ github.event.inputs.runtime_minutes }} * 60 ))
